version: '2'
services:
  openvpn:
    env_file: ".env.openvpn"
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: sshpanel-openvpn
    ports:
     - "1194:1194/udp"
    restart: unless-stopped
    volumes:
     - ./openvpn-data/conf:/etc/openvpn